inklabsfoundation/inkchain

settings.gradle

Add javenenv-image compile dependent file.

Add javenenv-image compile dependent file

---

scripts/colour.sh
scripts/download_inkchain.sh

add images download scripts

---

examples/map/map.go
examples/map/map_experimental.go
examples/marbles02/marbles_chaincode.go

Add some chaincode examples for inkchain.

Add chaincode examples

---

examples/cli_test/scripts/xc_test_queryTxInfo.sh
examples/cli_test/scripts/xc_test_registered.sh
examples/cli_test/scripts/xc_test_transferInk.sh
examples/cli_test/scripts/xc_test_unlock.sh
examples/cli_test/scripts/xc_upgrade.sh
examples/xcDemo/Xc.go

- change test scripts about fee amount
- xcDemo add validate txId function
- xcDemo unlock add an arg

test script change and xcDemo add methods

---

examples/cat/cat.go

Signed-off-by: grapebaba <281165273@qq.com>

Refine cat contract

---

examples/asset/asset.go

Signed-off-by: grapebaba <281165273@qq.com>

Refine asset contract

---

examples/inkwork/cfg.go
examples/inkwork/inkwork.go

add DApp INKwork

---

examples/xc/contract/ink-xc.sol
examples/xc/contract/xc-plugin.sol
examples/xcDemo/Xc.go

change unlock key
origin：platformName+pubTxId
now:platformName+"|"+pubTxId

change unlock key

---

examples/xc/contract/ink-token.sol
examples/xc/contract/ink-xc.sol
examples/xc/contract/xc-plugin.sol

modified :
examples/xc/contract/ink-token.sol 、
examples/xc/contract/ink-xc.sol、
examples/xc/contract/xc-plugin.sol .

modify method ’s modifier

---

examples/xc/contract/ink-xc.sol
examples/xc/contract/xc-plugin.sol

modify balanceOf data structs. modify methods.
1) modified:   examples/xc/contract/ink-xc.sol.
add&modify setAdmin、getAdmin、setPlatformName、getPlatformName、getStatus.
modify balanceOf. 
modify transaction amount 's validation.
2) modified:   examples/xc/contract/xc-plugin.sol.
add&modify setAdmin、getAdmin、getStatus.

modify data structs & methods.

---

examples/xc/contract/xc-plugin.sol

…n of the deletePlatform method. When callers are null, anyone can call the deletePlatform method.

The caller who adds a partial method to the contract.

---

core/scc/lscc/lscc.go

Make org member query chaincode
Signed-off-by: grapebaba <281165273@qq.com>

Change chaincode query policy

---

core/peer/config.go
core/scc/xscc/xscc.go
examples/cli_test/docker-compose-cross.yaml
sampleconfig/core.yaml

update config module: read publicPlatformPrivateKey from file
update docker-compose-cross.yaml

add validation of xscc initialization parameters

---

core/scc/xscc/xscc.go

update xscc: the balanceType parameter of the open lock method

Crosschain update

---

core/chaincode/shim/chaincode.go
core/chaincode/shim/interfaces.go
core/chaincode/shim/mockstub.go
examples/token/token.go

update ChaincodeStub: add QueryFee interface

add fee interface into token

---

core/chaincode/pubinfo_validate.go
core/peer/config.go
core/scc/xscc/xscc.go
core/wallet/wallet.go
examples/cli_test/docker-compose-cross.yaml
sampleconfig/core.yaml

add contract version to signature
reconstruct cross-chain configuration

reconstruct cross-chain configuration

---

examples/xc/eth-v1.0.2/INK.sol
examples/xc/eth-v1.0.2/SafeMath.sol
examples/xc/eth-v1.0.2/Token.sol
examples/xc/eth-v1.0.2/XC.sol
examples/xc/eth-v1.0.2/XCInterface.sol
examples/xc/eth-v1.0.2/XCPlugin.sol
examples/xc/eth-v1.0.2/XCPluginInterface.sol
examples/xc/eth-v1.0.2/compileToken.sh
examples/xc/eth-v1.0.2/compileXC.sh
examples/xc/eth-v1.0.2/compileXCP.sh
examples/xc/qtum-v1.0.2/INK.sol
examples/xc/qtum-v1.0.2/SafeMath.sol
examples/xc/qtum-v1.0.2/Token.sol
examples/xc/qtum-v1.0.2/XC.sol
examples/xc/qtum-v1.0.2/XCInterface.sol
examples/xc/qtum-v1.0.2/XCPlugin.sol
examples/xc/qtum-v1.0.2/XCPluginInterface.sol
examples/xc/qtum-v1.0.2/compileToken.sh
examples/xc/qtum-v1.0.2/compileXC.sh
examples/xc/qtum-v1.0.2/compileXCP.sh

xc contract v1.0.2

---

Makefile
core/chaincode/pubinfo_validate.go
core/peer/config.go
core/scc/xscc/xscc.go
sampleconfig/core.yaml

update cross-chain configuration:add supportToken and supportPlatform
update xscc: use "==" replace "<" when validate args
update pubinfo_validate: use constant replace number

update cross-chain configuration:add supportToken and supportPlatform

---

examples/xc/eth-v1.0.2/XC.sol
examples/xc/eth-v1.0.2/XCPlugin.sol
examples/xc/qtum-v1.0.2/Token.sol
examples/xc/qtum-v1.0.2/XC.sol
examples/xc/qtum-v1.0.2/XCPlugin.sol
examples/xc/qtum-v1.0.2/compileToken.sh
examples/xc/qtum-v1.0.2/compileXC.sh
examples/xc/qtum-v1.0.2/compileXCP.sh

 modify deletePublickey.

---

core/chaincode/shim/chaincode.go
core/chaincode/shim/interfaces.go
core/chaincode/shim/mockstub.go
core/wallet/wallet_utils.go

add GetSenderPubKey method for ChaincodeStub
